In [87]:
import pandas as pd
import re
import konlpy
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import font_manager, rc
import numpy as np
from tqdm import tqdm
import urllib.request
import warnings
warnings.filterwarnings("ignore")

In [88]:
df = pd.read_excel('data/_test.xlsx')

In [89]:
from konlpy.tag import Hannanum

hannanum = Hannanum()
okt = konlpy.tag.Okt()

def text_preprocess(x):
    text=[]
    a = re.sub('[^가-힣0-9a-zA-Z\\s]', '',x)
    for j in a.split():
        text.append(j)
    return ' '.join(text)

def tokenize(x):
    text = []
    tokens = okt.pos(x)
    for token in tokens :
        #if token[1] == 'Adjective' or token[1]=='Adverb' or token[1] == 'Noun' or token[1] == 'Verb' or 'Unknown':
        if token[1] == 'Noun' :
            if len(token[0])>1:
                text.append(token[0])
    return text

In [90]:
def get(x):
    result=""
    for i in x:
        if len(i)>1:
            
            i=i.replace("jpg","")
            if "갤" in i:
                continue
            result=result+" "+i
    return result

In [91]:
df

                                               제목                날짜
0                 메시, 역대 최다 7번째 '발롱도르' 수상…호날두는 6위  2021.11.30 21:19
1          콘테가 점찍은 '케인 후계자', 맨유까지 가세... 영입할 수 있을까  2021.11.30 21:17
2         1800억→675억...바르사 골칫덩이, 재계약 거부 후 '이적 추진'  2021.11.30 21:13
3                           여전한 '메시의 시대'…7번째 발롱도르  2021.11.30 21:04
4             레반도프스키 아내 "사랑해요 여보, 당신은 나에게 언제나 1등"  2021.11.30 21:04
..                                            ...               ...
175                메시, 7번째 발롱도르…2위 레반도프스키, 스트라이커賞  2021.11.30 11:51
176              '이러니 PSG 떠나지' 감출 수 없었던 음바페의 '썩소'  2021.11.30 11:51
177            '맨유 시한부 감독' 랑닉, 코칭스태프는 솔샤르 시절 그대로?  2021.11.30 11:51
178            김민재 토트넘行 위해 손흥민 나섰다?…"콘테 면담 통역 맡아"  2021.11.30 11:50
179  '발롱도르 수상' 메시, 613점 획득...호날두는 178점에 그치며 6위 기록  2021.11.30 11:50

[180 rows x 2 columns]

In [92]:
df['token'] = df['제목'].apply(lambda x : text_preprocess(x))
df['token']=df['token'].apply(lambda x : hannanum.nouns(x))
df['data']=df['token'].apply(lambda x: get(x))

In [93]:
df

,제목,날짜,token,data
0,"메시, 역대 최다 7번째 '발롱도르' 수상…호날두는 6위",2021.11.30 21:19,"[메시, 역대, 최다, 7번, 발롱도르, 수상호날두, 6위]",메시 역대 최다 7번 발롱도르 수상호날두 6위
1,"콘테가 점찍은 '케인 후계자', 맨유까지 가세... 영입할 수 있을까",2021.11.30 21:17,"[콘테, 케, 후계자, 맨유까지, 영입, 수, 있을까]",콘테 후계자 맨유까지 영입 있을까
2,"1800억→675억...바르사 골칫덩이, 재계약 거부 후 '이적 추진'",2021.11.30 21:13,"[1800억675억바르사, 골칫덩, 재계약, 거부, 후, 이적, 추진]",1800억675억바르사 골칫덩 재계약 거부 이적 추진
3,여전한 '메시의 시대'…7번째 발롱도르,2021.11.30 21:04,"[여전, 메시, 시대7번째, 발롱도르]",여전 메시 시대7번째 발롱도르
4,"레반도프스키 아내 ""사랑해요 여보, 당신은 나에게 언제나 1등""",2021.11.30 21:04,"[레반도프스키, 아내, 사랑, 당신, 나, 1등]",레반도프스키 아내 사랑 당신 1등
...,...,...,...,...
175,"메시, 7번째 발롱도르…2위 레반도프스키, 스트라이커賞",2021.11.30 11:51,"[메시, 7번, 발롱도르2위, 레반도프스키, 스트라이커]",메시 7번 발롱도르2위 레반도프스키 스트라이커
176,'이러니 PSG 떠나지' 감출 수 없었던 음바페의 '썩소',2021.11.30 11:51,"[이러니, 수, 음바페, 썩소]",이러니 음바페 썩소
177,"'맨유 시한부 감독' 랑닉, 코칭스태프는 솔샤르 시절 그대로?",2021.11.30 11:51,"[맨유, 시한부, 감독, 랑닉, 코칭스태프, 솔샤르, 시절]",맨유 시한부 감독 랑닉 코칭스태프 솔샤르 시절
178,"김민재 토트넘行 위해 손흥민 나섰다?…""콘테 면담 통역 맡아""",2021.11.30 11:50,"[김민재, 토트넘, 손흥민, 나섰다콘테, 면담, 통역]",김민재 토트넘 손흥민 나섰다콘테 면담 통역
179,"'발롱도르 수상' 메시, 613점 획득...호날두는 178점에 그치며 6위 기록",2021.11.30 11:50,"[발롱도르, 수상, 메시, 613점, 획득호날두, 178점, 6위, 기록]",발롱도르 수상 메시 613점 획득호날두 178점 6위 기록

In [94]:
vocab=list(set(w for doc in df['data'] for w in doc.split()))
vocab.sort()

In [95]:
vocab

['0골',
 '10',
 '11',
 '158만원',
 '15골',
 '178점',
 '1800억675억바르사',
 '1st',
 '1골',
 '1등',
 '1위',
 '1주년울버햄튼',
 '2000년대',
 '2020년대',
 '2021',
 '20대',
 '20살',
 '2168억',
 '23위',
 '2명',
 '2부리그행',
 '2월',
 '2위',
 '2위마테우스',
 '30대',
 '32',
 '36회UCL',
 '3위',
 '523억',
 '533일',
 '5가지',
 '5가지게겐프레싱',
 '5날두14년간',
 '5명',
 '5부',
 '600억',
 '613점',
 '6위',
 '6주',
 '7G만',
 '7th',
 '7등',
 '7발롱',
 '7번',
 '7위',
 '800억',
 '9233',
 '940억',
 '9위',
 'FW그래',
 'TOP10',
 'TOP3',
 'U20',
 '가격',
 '가능성',
 '가담',
 '간절',
 '감독',
 '감동',
 '갑부',
 '강등',
 '개최',
 '개최대진',
 '거부',
 '거절',
 '거짓말',
 '걸림돌',
 '격분',
 '격분살라',
 '결과',
 '결정',
 '결정적',
 '결정주급',
 '경기상위권',
 '경쟁',
 '경질',
 '경질리그1',
 '경험',
 '계획',
 '고려',
 '고민',
 '골절',
 '골칫덩',
 '공개',
 '공격',
 '공격수',
 '공격수아약스행',
 '공식',
 '공인구',
 '공정',
 '공통',
 '과거현재미래',
 '관련',
 '관심',
 '관심스왑딜',
 '구단',
 '구두',
 '구두합',
 '구성',
 '구애',
 '군침',
 '굿바',
 '귄도안',
 '그림',
 '극찬',
 '급구',
 '기록',
 '기자',
 '기자단',
 '기준',
 '김민재',
 '까불어퍼디난드',
 '나섰다콘테',
 '나와',
 '나폴리',
 '난항',
 '남녀',
 '남매',
 '내년',
 '냉철',
 '네덜란드',
 '노르웨',
 '노리치전',
 '노쇼',
 '논란',
 '논란들',
 '농담이지',
 '누구',
 '눈길',
 '뉴시스Pic',
 '뉴캐슬',
 '능가',
 '능력',
 '다행',
 '당신',
 '대단해',
 '대동단결2년',
 '대만족',
 '대전',
 '대진표',
 '대체자',
 '대폭',
 '대표',
 '대표팀',
 '대화',
 '더비',
 '데뷔',
 '데뷔전',
 '데뷔전최다',
 '데포',
 '도달',
 '도밍게스',
 '돈값',
 '동료',
 '동료들',
 '동의',
 '동의2020',
 '두개골',
 '두근두근1월',
 '듀오',
 '드로그바',
 '득표',
 '등장',
 '디렉터',
 '때문',
 '라리',
 '라리가',
 '라멜라',
 '라모스',
 '라이스',
 '라이프치',
 '라인업',
 '랄프',
 '랑닉',
 '랑닉에',
 '랭킹',
 '레반도프스키',
 '레반도프스키한테',
 '레반테',
 '레알',
 '레전드',
 '로마',
 '로마노',
 '로저스',
 '루머에프리미어리그',
 '리그',
 '리네커',
 '리버풀',
 '리오넬',
 '마디24살',
 '마지막',
 '마테우스',
 '망토',
 '매료',
 '매체',
 '맨시티',
 '맨시티뉴욕',
 '맨시티맨유',
 '맨유',
 '맨유까지',
 '맨유행',
 '먹튀',
 '메날두',
 '메르텐스',
 '메시',
 '메시vs레반돕',
 '메시벤제마중원은',
 '메시에',
 '메시역대',
 '메시통산',
 '메시호날두',
 '멕시코',
 '멘디',
 '면담',
 '면담통역',
 '명가',
 '명불허전',
 '모델',
 '모드리치',
 '목표',
 '몬스터',
 '몸값',
 '무리뉴',
 '문제',
 '뭉치',
 '뮌헨',
 '미래',
 '민재야',
 '바르사',
 '바르셀로',
 '반박',
 '반응',
 '발렌시',
 '발롱',
 '발롱도',
 '발롱도르',
 '발롱도르2위',
 '발롱도르라이벌',
 '발롱도르이제',
 '방법',
 '방송',
 '방송인',
 '방안',
 '방출',
 '배경',
 '베스트',
 '베스트11',
 '베테랑',
 '벤제마',
 '벤치',
 '변화',
 '복귀',
 '본격화',
 '볼로냐',
 '부상',
 '부정',
 '부정적',
 '분노',
 '분모',
 '분통',
 '불가능',
 '불발',
 '불참',
 '불쾌',
 '불혹',
 '브라질',
 '비PK골',
 '비상',
 '비자코',
 '비주전',
 '비크',
 '비판역대',
 '빅클럽들',
 '빠졌다PSG',
 '사랑',
 '사랑여전',
 '사비',
 '사수올',
 '사실상',
 '살림꾼',
 '생각',
 '생명',
 '선두선수',
 '선발',
 '선수',
 '선수들',
 '선정',
 '설득에도뤼디거',
 '설문',
 '설문조사',
 '성공',
 '성적',
 '성찰',
 '세계',
 '센터백',
 '소개',
 '소급',
 '소름돋',
 '소식',
 '소식통',
 '속옷',
 '손흥민',
 '손흥민에게',
 '손흥민조소현',
 '솔샤르',
 '수네스',
 '수비',
 '수비수',
 '수상',
 '수상자',
 '수상해',
 '수상호날두',
 '수상호날두레반도프스키',
 '수상흐뭇',
 '수준토트넘',
 '숙제',
 '순위',
 '슈퍼리그',
 '슈퍼스타',
 '슈퍼카',
 '스몰링',
 '스카마카',
 '스콜스',
 '스타',
 '스트라이커',
 '스포츠타',
 '스폰서',
 '승리',
 '시대',
 '시대7번째',
 '시도최다',
 '시상식',
 '시선',
 '시절',
 '시즌',
 '시큰둥',
 '시티',
 '시한부',
 '신문',
 '신성',
 '실시',
 '실패',
 '싹쓸',
 '싹쓸이한',
 '쌤에',
 '썩소',
 '아내',
 '아다마',
 '아들',
 '아래',
 '아버지',
 '아빠',
 '아스날전',
 '아스날전서',
 '아스널',
 '아스널전',
 '아시아',
 '아약스',
 '아이다라',
 '아자르',
 '알렉시아',
 '압박',
 '앰버서더',
 '야망',
 '야신상클린시트',
 '양심',
 '얼마',
 '없나재계약마저',
 '에드워즈',
 '엔진',
 '여러분',
 '여전',
 '역대',
 '역사',
 '역사상',
 '연기',
 '연기력침대축구',
 '연속',
 '열흘',
 '영웅',
 '영원',
 '영입',
 '영입라이프치',
 '영입생',
 '영입전',
 '예상',
 '예언',
 '오피셜',
 '올해',
 '완전',
 '외면',
 '요청',
 '우레',
 '우리',
 '우상',
 '우승',
 '우승캐러거',
 '운동',
 '울브스',
 '웃참',
 '원정',
 '원한다바르사',
 '원한다스카우터',
 '원한다아르헨티',
 '원해',
 '월드컵',
 '월클',
 '웨스트햄',
 '위장염',
 '위촉',
 '위해울브스',
 '윙어',
 '유망주',
 '유벤투스',
 '유일무이',
 '유출4년',
 '은퇴',
 '음바페',
 '음바페홀란드',
 '응원',
 '의리',
 '의혹',
 '의혹700억',
 '이강',
 '이러니',
 '이름',
 '이번',
 '이상한',
 '이스탄불',
 '이야기',
 '이용',
 '이유',
 '이적',
 '이탈리아',
 '이해',
 '이형주',
 '인기',
 '인기투표',
 '인물',
 '인종차별유리몸',
 '인하',
 '일침',
 '임명',
 '임명안정감',
 '임시',
 '있네맨유',
 '있을까',
 '자격',
 '자랑',
 '장난',
 '장전',
 '재계약',
 '재정',
 '재현',
 '저격',
 '저리가',
 '적중메시',
 '전설',
 '전쟁',
 '전치',
 '절친',
 '점유',
 '정상적',
 '정신력',
 '정조준',
 '정했다아스널',
 '제외',
 '조건',
 '조르지뉴',
 '조작',
 '조합',
 '종결호날두',
 '종지부',
 '좌절',
 '죄야랑닉',
 '주장',
 '주최',
 '주최사',
 '중반',
 '중원',
 '즉위식에펠탑',
 '지목',
 '지속바르셀로',
 '지휘',
 '지휘봉',
 '집중',
 '차비',
 '참전',
 '창피',
 '챔스',
 '처음이지모예스반',
 '체재',
 '체제',
 '첼시',
 '첼시전',
 '최고',
 '최다',
 '최악',
 '최저',
 '최전방',
 '추락',
 '추월',
 '추진',
 '추진손흥민',
 '축구',
 '축구환상곡',
 '축하',
 '축하해',
 '출신',
 '출신들',
 '충격',
 '캐러거',
 '캡틴',
 '커리',
 '케릭',
 '케인',
 '케인보다',
 '코칭스태프',
 '코파',
 '콘테',
 '크로스',
 '크루이프',
 '클래스',
 '클럽월드컵',
 '키예르',
 '킨캐러거',
 '터키',
 '터키발',
 '토트넘',
 '토트넘서',
 '통산',
 '통역',
 '통합',
 '투표',
 '투헬',
 '트로피',
 '특급',
 '티키타카',
 '파격',
 '파견',
 '파티',
 '팔기로그래',
 '팔아먹지',
 '패스',
 '팩폭',
 '팬티',
 '퍼디난드',
 '페레이라',
 '펠레',
 '포그바',
 '포로',
 '포지션',
 '포착',
 '포체티노나쁜',
 '폭탄',
 '표정',
 '푸스카스상',
 '풀리시치',
 '품격',
 '프랑스',
 '피지컬',
 '피해자',
 '필요',
 '필요해',
 '하이다',
 '한국',
 '한숨',
 '한준',
 '한탄',
 '할리우드',
 '할무리뉴솔샤르랑닉',
 '합당하다강탈당했다',
 '합의',
 '해결',
 '해명',
 '행복',
 '행운',
 '헤아',
 '헬프',
 '호나우지뉴to메시',
 '호날두',
 '호날두메시토레스올해',
 '호날두보다',
 '혹평',
 '혼자',
 '홀란드',
 '홍보대사',
 '화제',
 '확정',
 '활용법',
 '황금공배려',
 '황제',
 '황희찬',
 '황희찬에',
 '회계',
 '회장발롱',
 '획득호날두',
 '횟수',
 '후계자',
 '후보',
 '희망',
 '히메네스']

In [96]:
def count_df(t,df):
    count=0
    for i in range(len(df)):
        for j in df.loc[i,'token']:
            if j==t:
                count=count+1
    return count

In [98]:
result=[]
for i in range(len(vocab)):
    t=vocab[i]
    result.append(count_df(t,df))
result=pd.DataFrame(result, index=vocab, columns=['DF'])
result

       DF
0골      1
10      1
11      1
158만원   1
15골     1
...    ..
횟수      1
후계자     1
후보      5
희망      3
히메네스    1

[602 rows x 1 columns]

In [99]:
result=result.sort_values(by=['DF'],ascending=False)
result

      DF
발롱도르  50
메시    39
랑닉    20
토트넘   18
7번    17
...   ..
모델     1
명불허전   1
명가     1
면담통역   1
히메네스   1

[602 rows x 1 columns]

In [101]:
result.head(10)

        DF
발롱도르    50
메시      39
랑닉      20
토트넘     18
7번      17
호날두     15
감독      12
맨유      12
수상      11
레반도프스키  10